### PR TITLE
fix(yarn): correctly preserve prefix

### LINKED ISSUE #22: Travis + Yarn not updating lockfile
Just got first PR after initial config with greenkeeper-lockfile. This is the output from travis:

```
$ greenkeeper-lockfile-update
error Received malformed response from registry for undefined. The registry may be down.
child_process.js:526
    throw err;
    ^
Error: Command failed: yarn add -D --save-prefix="" ember-cli-mirage@0.3.2
error Received malformed response from registry for undefined. The registry may be down.
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at updateLockfile (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/lib/update-lockfile.js:26:7)
    at Module.update [as exports] (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/update.js:49:3)
    at Object.<anonymous> (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/update.js:56:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
The command "greenkeeper-lockfile-update" failed and exited with 1 during .
```

```
$ node --version
v6.9.2
$ npm --version
3.10.9
$ nvm --version
0.33.2
```

`--save-prefix` does not appear to be a valid option for yarn.

### PR DESCRIPTION
**Pull request by boennemann**
This should address #22.

Closes #22

### CODE REVIEW

**Comment by john-griffin** [comment]
Thanks for the fix, would this still work with `^`?

**Comment by boennemann** [comment]
As far as the docs go `^` is the default behavior, but there is now way to explicitly set it. Also no way to set `>=` etc. For all those cases it will simply fall back to the default behavior.

I'll go ahead and merge this now, as it'll definitely be less broken than what's out there right now.
Please let me know how it goes, and thanks again for reporting :)

Best,
Stephan

**Comment by boennemann** [comment]
Here you go: https://github.com/greenkeeperio/greenkeeper-lockfile/releases/tag/v1.3.2

**Comment by john-griffin** [comment]
Thanks, I reran the build that was failing on travis after `1.3.2` was published and `yarn.lock` update commit was pushed correctly.

**Comment by boennemann** [comment]
Yay 🎉 
Thanks again for reporting :)

**Pull request merged**
