### PR TITLE
feat: basic wercker support

### PR DESCRIPTION
**Pull request by misund**

### CODE REVIEW

**Comment by christophwitzko** [comment]
@misund awesome, thanks. ☺️

**Comment by tdeekens** [comment]
Thanks a lot for the addition. Just a little question: is it intended to add the `WERCKER` env variable to the workflow as it's not one of the [available env variables](http://devcenter.wercker.com/docs/environment-variables/available-env-vars)?

**Comment by misund** [comment]
The `WERCKER` env var is set even though it's not documented.

**Comment by tdeekens** [comment]
Alright. Then we just need to release the package as `1.7`. Thanks for the contribution!

**Comment by christophwitzko** [comment]
`greenkeeper-lockfile@1.7.0` is now released. 🎉

**Pull request merged**
