### PR TITLE
Codeship CI Integration

### PR DESCRIPTION
**Pull request by selbyk**
Implements support for Codeship Pro, updates lockfile on commit messages matching `/^(chore|fix)\(package\): update [^ ]+ to version.*$/mi`

https://github.com/greenkeeperio/greenkeeper-lockfile/issues/25

### CODE REVIEW

**Comment by StephanBijzitter** [comment]
@janl Since the author is not responding and we also really want this feature:

Codeship does not provide any information that is used by this package on other services to detect the state of the branch. There's only one way to know whether Greenkeeper has already commited on a branch to then update the lockfile and that is by parsing the commit message.

This change does indeed limit Greenkeeper to stick to a specific pattern for commit messages, but that's really the only limitation introduced by this pull request. Even then, if users are (in the future) able to customise these messages, it could simply ignore the customisation on Codeship and stick to the default pattern.

**Comment by selbyk** [comment]
@janl Sorry for the delayed response, but this has been put on the backburner for the past month or so.  I initially tried using the techniques used in the other CI implementations, but `gitHelpers.getNumberOfCommitsOnBranch` was sporadically returning an incorrect value for some reason.  I'm not actually sure what `correctBuild` should be a switch for, but Codeship doesn't have an environment variable exposed saying wether a build represents a PR, like I see some other implementations doing.

Can you clarify what being usable without semantic-release means?  I'd be happy to make adjustments where necessary to get this merged in, but we've been using it in the current state for a couple months now.

**Comment by janl** [comment]
Thanks for the explanation

**Comment by Realtin** [comment]
Thank you @selbyk for your work and @StephanBijzitter for the explanation ✨ 🌴

**Comment by Realtin** [comment]
Oh no! I squashed the commits and now it's all under my name. I'm so sorry 😢

**Comment by StephanBijzitter** [comment]
@Realtin 
> @selbyk committed with @Realtin feat: add basic Codeship CI Integration
Looks good to me ;-)

**Pull request merged**
