### PR TITLE
fix: Jenkins multibranch

### PR DESCRIPTION
**Pull request by sgtcoolguy**
This is a follow-on to #165

`greenkeeper-lockfile-upload` will ignore `gitURL` and use `repoSlug` when using the `env.GH_TOKEN` (see https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/upload.js#L47-L48). I did not attempt to fix that, but instead overhauled the jenkins CI impl to provide both `gitURL` and `repoSlug`.

I also tweaked it to be much more exhaustive in attempting to get the git URL (and therefore the slug) by consulting, in order:
- `env.CHANGE_TARGET` - used by Jenkins multibranch builds.
- `env.GIT_URL` - used by old Jenkins plugins.
- calling out to `git config remote.origin.url`
- Trying the `repository`/`repository.url` value from package.json.

### CODE REVIEW

**Comment by patkub** [comment]
@sgtcoolguy Travis build fails because of code format. Run `standard --fix` and commit changes to resolve.

**Comment by janl** [comment]
@sgtcoolguy heya, overall this looks great. Can you look at the test errors reported by Travis?

**Comment by sgtcoolguy** [comment]
@janl ok, I think I fixed the issue now. Needed to update the test setup/snapshot to handle/expect a call to `git config remote.origin.url` (actually twice in the monorepo root package case)

**Comment by janl** [comment]
perfect, thanks!

**Pull request merged**
