### PR TITLE
AppVeyor CI Integration

### PR DESCRIPTION
**Pull request by patkub**
An attempt at getting `greenkeeper-lockfile` working in AppVeyor CI.
AppVeyor Build that updated lockfile: https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.20
Greenkeeper PR where lockfile was updated: https://github.com/patkub/test-greenkeeper-lockfile-appveyor/pull/2

Issues:

- AppVeyor runs Windows, so the existing git commands won't work. How should I go about detecting AppVeyor CI in `update-lockfile.js`?
- May break in other places where `exec` runs linux commands

### CODE REVIEW

**Comment by janl** [comment]
> AppVeyor runs Windows, so the existing git commands won't work. How should I go about detecting AppVeyor CI in update-lockfile.js?

Why wouldn’t these commands work on Windows?

**Comment by patkub** [comment]
@janl 

- The Windows equivalent of piping output to `2>/dev/null` is `>NUL`. (https://stackoverflow.com/questions/313111/dev-null-in-windows).

- `true` is not recognized as a command in Windows. To get a truthful value, `(exit 0)` creates a new shell with exit status 0 which means success (https://stackoverflow.com/a/22071169/8234763)

- `exec(git commit -m "${updateMessage}")` doesn't work because Windows doesn't have process substitution and can't evaluate $(updateMessage).

**Comment by patkub** [comment]
I added a check to run the Windows git commands and got a passing build.
https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.23

**Comment by chgibb** [comment]
Would it not be possible to run through MSYS on Appveyor? With some minor tweaking, shell scripts written for Travis will work fine on Appveyor under MSYS.

**Comment by patkub** [comment]
@chgibb I tried running just the ci-services implementation through MSYS on Appveyor and the git commit command fails.
https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.58

I installed `greenkeeper-lockfile` globally with `npm install -g patkub/greenkeeper-lockfile#appveyor-msys`. However, running `greenkeeper-lockfile` through msys looks for `update-lockfile.js` in the local `node_modules` directory instead of the global location.

Installing `greenkeeper-lockfile` locally without modifying `package.json` gets it to run, but still fails on the git commit -m command.

appveyor.yml: https://github.com/patkub/test-greenkeeper-lockfile-appveyor/blob/master/appveyor.yml

**Comment by chgibb** [comment]
@patkub Can you send me a link to ```patkub/greenkeeper-lockfile#appveyor-msys```?

**Comment by patkub** [comment]
@chgibb Yes. I just cherry-picked the `add appveyor to ci-services` commit from here.
https://github.com/patkub/greenkeeper-lockfile/tree/appveyor-msys

**Comment by chgibb** [comment]
This 
```
  exec('git add npm-shrinkwrap.json 2>/dev/null || true')
  exec('git add package-lock.json 2>/dev/null || true')
  exec('git add yarn.lock 2>/dev/null || true')
  exec('git config user.email "support@greenkeeper.io"')
  exec('git config user.name "greenkeeper[bot]"')
```
will fail if run through node directly.

Instead of ```C:\MinGW\msys\1.0\bin\sh greenkeeper-lockfile-update```, something like ```bash node ./node_modules/.bin/greenkeeper-lockfile-update``` should work. As long as you can get ```bash``` to invoke ```node``` to invoke ```greenkeeper-lockfile-update```, as opposed to ```cmd``` or ```ps```(which is the default Appveyor uses in its config).

**Comment by patkub** [comment]
@chgibb It looks like even though I get `bash` to invoke `node` to invoke `greenkeeper-lockfile-update`, the commands still fail to run in a `bash` environment. I tried two approaches:

1. https://github.com/patkub/test-greenkeeper-lockfile-appveyor/commit/20641a314022e4abc6993790108e26c401a153c7

I used the regular `bash` command available in Appveyor to run `node greenkeeper-lockfile/update.js`. The command passes on master, but fails to commit on a greenkeeper branch.
master: https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.97
greenkeeper: https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.98

2. https://github.com/patkub/test-greenkeeper-lockfile-appveyor/commit/d3f509e5e88e5bbe21c0c97a6c739f269b768ad5

Using `msys bash` to invoke `node` to invoke `greenkeeper-lockfile/update.js` also passes on master, but fails to commit on a greenkeeper branch.
master: https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.99
greenkeeper: https://ci.appveyor.com/project/patkub/test-greenkeeper-lockfile-appveyor/build/1.0.100

**Comment by chgibb** [comment]
@patkub you're probably correct. I was hoping ```exec``` would spawn a new instance of the current shell (hence, trying to invoke through ```bash```). You might want to look at invoking ```git``` through ```cp.spawnSync``` and then just discarding the buffered ```stdio``` output to get the same behaviour as ```exec``` with the redirect.

**Comment by patkub** [comment]
@chgibb @janl How about checking if running on windows, and using `exec` to run windows compatible git commands? I added a check for Windows and git commands to commit the updated lockfile here. This work, but could make the package more complex, and other commands run though `exec` also need to be changed to work on Windows.

**Comment by xt0rted** [comment]
AppVeyor supports Linux too now https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

**Pull request closed without merging**
